version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words:
  - Centisecond
  - Centiseconds
  - cfmakeraw
  - Coalescible
  - COLORTERM
  - CTYPE
  - Deque
  - EAGAIN
  - EWOULDBLOCK
  - Ghostty
  - Libc
  - NONBLOCK
  - Nonsending
  - preconcurrency
  - Sparkline
  - Sparklines
  - syscall
  - truecolor
  - uppercased
ignoreWords: []
import: []
