[tools]
bun = "latest"
prek = "latest"

[tasks.release_core]
description = "Build core for release"
run = [
  "cd $MISE_PROJECT_ROOT",
  "swift build -c release"
]

[tasks.release_ex_web]
description = "Build web for release"
run = [
  "swift build -c release --package-path Platforms/Web",
  "bun run build Platforms/Web"
]
depends = ['release_core']
