import Foundation
import Testing

@testable import TerminalUI

@Suite
struct TerminalRenderStyleCodecTests {
  @Test("codec decodes a literal payload generated by WebTUI")
  func decodesLiteralWebTUIPayload() throws {
    let decoded = try #require(
      TerminalRenderStyleCodec.decodeBase64(webTUIDefaultDarkEncodedRenderStyle)
    )

    #expect(decoded == webTUIDefaultDarkRenderStyle())
  }

  @Test("codec encodes canonical JSON with theme fields in stable order")
  func encodesCanonicalJSONWithTheme() throws {
    let style = TerminalRenderStyle(
      appearance: .init(
        foregroundColor: .hex("#102030"),
        backgroundColor: .hex("#405060"),
        tintColor: .hex("#708090"),
        palette: [
          7: .hex("#777777"),
          0: .hex("#000000"),
          15: .hex("#FFFFFF"),
        ],
        colorScheme: .dark,
        colorSchemeContrast: .increased,
        source: .override
      ),
      theme: .init(
        foreground: .hex("#ABCDEF"),
        background: .hex("#012345"),
        tint: .hex("#456789"),
        separator: .hex("#111111"),
        selection: .hex("#222222"),
        placeholder: .hex("#333333"),
        link: .hex("#444444"),
        fill: .hex("#555555"),
        windowBackground: .hex("#666666"),
        success: .hex("#777777"),
        warning: .hex("#888888"),
        danger: .hex("#999999"),
        info: .hex("#AAAAAA"),
        muted: .hex("#BBBBBB")
      )
    )

    let encoded = try #require(TerminalRenderStyleCodec.encodeBase64(style))
    let json = try #require(decodedJSONString(fromBase64: encoded))

    #expect(
      json
        == ##"{"appearance":{"foregroundColor":"#102030","backgroundColor":"#405060","tintColor":"#708090","palette":{"0":"#000000","7":"#777777","15":"#FFFFFF"},"colorScheme":"dark","colorSchemeContrast":"increased","source":"override"},"theme":{"foreground":"#ABCDEF","background":"#012345","tint":"#456789","separator":"#111111","selection":"#222222","placeholder":"#333333","link":"#444444","fill":"#555555","windowBackground":"#666666","success":"#777777","warning":"#888888","danger":"#999999","info":"#AAAAAA","muted":"#BBBBBB"}}"##
    )
  }

  @Test("codec omits theme when nil and sorts palette keys numerically")
  func omitsThemeAndSortsPaletteKeys() throws {
    let style = TerminalRenderStyle(
      appearance: .init(
        foregroundColor: .hex("#112233"),
        backgroundColor: .hex("#445566"),
        tintColor: .hex("#778899"),
        palette: [
          10: .hex("#0A0A0A"),
          2: .hex("#020202"),
          1: .hex("#010101"),
        ],
        colorScheme: .dark,
        colorSchemeContrast: .standard,
        source: .override
      ),
      theme: nil
    )

    let encoded = try #require(TerminalRenderStyleCodec.encodeBase64(style))
    let json = try #require(decodedJSONString(fromBase64: encoded))

    #expect(
      json
        == ##"{"appearance":{"foregroundColor":"#112233","backgroundColor":"#445566","tintColor":"#778899","palette":{"1":"#010101","2":"#020202","10":"#0A0A0A"},"colorScheme":"dark","colorSchemeContrast":"standard","source":"override"}}"##
    )
  }

  @Test(
    "codec rejects invalid base64, malformed JSON, invalid hex, unknown enums, and non-integer palette keys"
  )
  func rejectsInvalidPayloads() {
    let invalidPayloads = [
      "not base64!",
      base64EncodedJSON(##"{"appearance":{"foregroundColor":"#FFFFFF""##),
      base64EncodedJSON(
        baseTransportJSON.replacingOccurrences(of: "#D4D4D4", with: "not-a-hex")
      ),
      base64EncodedJSON(
        baseTransportJSON.replacingOccurrences(of: "\"dark\"", with: "\"night\"")
      ),
      base64EncodedJSON(
        baseTransportJSON.replacingOccurrences(
          of: "\"palette\":{\"0\":\"#000000\"}",
          with: "\"palette\":{\"accent\":\"#000000\"}"
        )
      ),
    ]

    for payload in invalidPayloads {
      #expect(TerminalRenderStyleCodec.decodeBase64(payload) == nil)
    }
  }
}

private let webTUIDefaultDarkEncodedRenderStyle =
  "eyJhcHBlYXJhbmNlIjp7ImZvcmVncm91bmRDb2xvciI6IiNkNGQ0ZDQiLCJiYWNrZ3JvdW5kQ29sb3IiOiIjMWUxZTFlIiwidGludENvbG9yIjoiIzExYThjZCIsInBhbGV0dGUiOnsiMCI6IiMwMDAwMDAiLCIxIjoiI2NkMzEzMSIsIjIiOiIjMGRiYzc5IiwiMyI6IiNlNWU1MTAiLCI0IjoiIzI0NzJjOCIsIjUiOiIjYmMzZmJjIiwiNiI6IiMxMWE4Y2QiLCI3IjoiI2U1ZTVlNSIsIjgiOiIjNjY2NjY2IiwiOSI6IiNmMTRjNGMiLCIxMCI6IiMyM2QxOGIiLCIxMSI6IiNmNWY1NDMiLCIxMiI6IiMzYjhlZWEiLCIxMyI6IiNkNjcwZDYiLCIxNCI6IiMyOWI4ZGIiLCIxNSI6IiNlNWU1ZTUifSwiY29sb3JTY2hlbWUiOiJkYXJrIiwiY29sb3JTY2hlbWVDb250cmFzdCI6ImluY3JlYXNlZCIsInNvdXJjZSI6Im92ZXJyaWRlIn0sInRoZW1lIjp7ImZvcmVncm91bmQiOiIjZDRkNGQ0IiwiYmFja2dyb3VuZCI6IiMxZTFlMWUiLCJ0aW50IjoiIzExYThjZCIsInNlcGFyYXRvciI6IiM2NjY2NjYiLCJzZWxlY3Rpb24iOiIjMjY0Zjc4IiwicGxhY2Vob2xkZXIiOiIjNjY2NjY2IiwibGluayI6IiMyNDcyYzgiLCJmaWxsIjoiIzJiMzAzYiIsIndpbmRvd0JhY2tncm91bmQiOiIjMWUxZTFlIiwic3VjY2VzcyI6IiMwZGJjNzkiLCJ3YXJuaW5nIjoiI2U1ZTUxMCIsImRhbmdlciI6IiNjZDMxMzEiLCJpbmZvIjoiIzExYThjZCIsIm11dGVkIjoiIzY2NjY2NiJ9fQ=="

private let baseTransportJSON =
  ##"{"appearance":{"foregroundColor":"#D4D4D4","backgroundColor":"#1E1E1E","tintColor":"#11A8CD","palette":{"0":"#000000"},"colorScheme":"dark","colorSchemeContrast":"increased","source":"override"}}"##

private func webTUIDefaultDarkRenderStyle() -> TerminalRenderStyle {
  .init(
    appearance: .init(
      foregroundColor: .hex("#d4d4d4"),
      backgroundColor: .hex("#1e1e1e"),
      tintColor: .hex("#11a8cd"),
      palette: [
        0: .hex("#000000"),
        1: .hex("#cd3131"),
        2: .hex("#0dbc79"),
        3: .hex("#e5e510"),
        4: .hex("#2472c8"),
        5: .hex("#bc3fbc"),
        6: .hex("#11a8cd"),
        7: .hex("#e5e5e5"),
        8: .hex("#666666"),
        9: .hex("#f14c4c"),
        10: .hex("#23d18b"),
        11: .hex("#f5f543"),
        12: .hex("#3b8eea"),
        13: .hex("#d670d6"),
        14: .hex("#29b8db"),
        15: .hex("#e5e5e5"),
      ],
      colorScheme: .dark,
      colorSchemeContrast: .increased,
      source: .override
    ),
    theme: .init(
      foreground: .hex("#d4d4d4"),
      background: .hex("#1e1e1e"),
      tint: .hex("#11a8cd"),
      separator: .hex("#666666"),
      selection: .hex("#264f78"),
      placeholder: .hex("#666666"),
      link: .hex("#2472c8"),
      fill: .hex("#2b303b"),
      windowBackground: .hex("#1e1e1e"),
      success: .hex("#0dbc79"),
      warning: .hex("#e5e510"),
      danger: .hex("#cd3131"),
      info: .hex("#11a8cd"),
      muted: .hex("#666666")
    )
  )
}

private func decodedJSONString(
  fromBase64 encoded: String
) -> String? {
  guard let data = Data(base64Encoded: encoded) else {
    return nil
  }

  return String(decoding: data, as: UTF8.self)
}

private func base64EncodedJSON(
  _ json: String
) -> String {
  Data(json.utf8).base64EncodedString()
}
