#!/usr/bin/env sh

set -eu

repo_root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
cd "$repo_root"

update=0
for argument in "$@"; do
  case "$argument" in
  --update)
    update=1
    ;;
  *)
    >&2 echo "Usage: Scripts/check_accessibility_guardrails.sh [--update]"
    exit 2
    ;;
  esac
done

failures=0

fail() {
  >&2 echo "$1"
  failures=1
}

manifest_entries() {
  manifest=$1

  if [ -f "$manifest" ]; then
    sed -E \
      -e 's/[[:space:]]*#.*$//' \
      -e '/^[[:space:]]*$/d' \
      "$manifest" | LC_ALL=C sort -u
  fi
}

write_manifest() {
  manifest=$1
  title=$2
  current=$3

  {
    echo "# $title"
    echo "#"
    echo "# Generated by Scripts/check_accessibility_guardrails.sh --update."
    echo "# New entries require accessibility review before this manifest is updated."
    cat "$current"
  } >"$manifest"
}

check_manifest() {
  title=$1
  manifest=$2
  current=$3

  if [ "$update" -eq 1 ]; then
    write_manifest "$manifest" "$title" "$current"
    return
  fi

  expected=$(mktemp "/tmp/swift-tui-a11y-expected.XXXXXX")
  manifest_entries "$manifest" >"$expected"

  if ! diff -u "$expected" "$current" >/tmp/swift-tui-a11y-diff.$$; then
    fail "$title changed. Review the new accessibility risk and rerun Scripts/check_accessibility_guardrails.sh --update only after the source is labeled, hidden, summarized, or explicitly accepted."
    >&2 cat /tmp/swift-tui-a11y-diff.$$
  fi

  rm -f "$expected" /tmp/swift-tui-a11y-diff.$$
}

swift_source_roots() {
  for directory in Sources Platforms Examples; do
    if [ -d "$directory" ]; then
      printf '%s\n' "$directory"
    fi
  done
}

scan_raw_glyph_sources() {
  # Box drawing, block drawing, braille, geometric state markers, and common
  # success/error symbols. These glyphs are allowed, but new source files that
  # introduce them must be reviewed for accessible text alternatives.
  rg -l \
    --glob '*.swift' \
    --glob '!**/Tests/**' \
    --glob '!**/.build/**' \
    -- '[✓✔✗✕●○◉◁▷▲▼▶◀◆◇◈▰▱▁▂▃▄▅▆▇█░▒▓▏▎▍▌▋▊▉▐─│┌┐└┘├┤┬┴┼╭╮╰╯┏┓┗┛╔╗╚╝║═╱╲⠁-⣿]' \
    $(swift_source_roots) 2>/dev/null | LC_ALL=C sort -u || true
}

scan_color_state_sources() {
  # File-level heuristic: state words near foreground/background/tint styling
  # are not automatically wrong, but new files should get review for a
  # non-color channel such as text, glyph, position, role, label, or hint.
  rg -l -P \
    --glob '*.swift' \
    --glob '!**/Tests/**' \
    --glob '!**/.build/**' \
    -- '(is[A-Za-z]*(Selected|Focused|Active|Disabled)|selected|focused|active|disabled|success|warning|error|tone).{0,120}(foregroundStyle|foregroundColor|background|tint|AnyShapeStyle|SemanticShapeStyle)|(foregroundStyle|foregroundColor|background|tint|AnyShapeStyle|SemanticShapeStyle).{0,120}(is[A-Za-z]*(Selected|Focused|Active|Disabled)|selected|focused|active|disabled|success|warning|error|tone)' \
    $(swift_source_roots) 2>/dev/null | LC_ALL=C sort -u || true
}

scan_visual_content_sources() {
  # Visual-only surfaces must either publish accessibility semantics, be hidden
  # from assistive technology, or be explicitly accepted by the visual-content
  # policy. This manifest keeps new call sites visible to review.
  rg -l -P \
    --glob '*.swift' \
    --glob '!**/Tests/**' \
    --glob '!**/.build/**' \
    -- '\b(Canvas|Image|AnimatedImage|Sparkline|Meter|BarChart|BulletChart|ComparisonChart|ThresholdGauge|ColumnChart|StackedBarChart|HeatStrip|Timeline)\s*\(' \
    $(swift_source_roots) 2>/dev/null | LC_ALL=C sort -u || true
}

check_listening_docs() {
  doc="Tests/SwiftTUITests/Accessibility/README.md"

  if [ ! -f "$doc" ]; then
    fail "$doc must document manual accessibility listening coverage."
    return
  fi

  for required in \
    "VoiceOver" \
    "NVDA" \
    "Orca" \
    "browser" \
    "accessible" \
    "visual-only" \
    "AccessibilityAnnouncer"; do
    if ! rg -n --fixed-strings --quiet -- "$required" "$doc"; then
      fail "$doc must mention $required."
    fi
  done
}

raw_current=$(mktemp "/tmp/swift-tui-a11y-raw.XXXXXX")
color_current=$(mktemp "/tmp/swift-tui-a11y-color.XXXXXX")
visual_current=$(mktemp "/tmp/swift-tui-a11y-visual.XXXXXX")

scan_raw_glyph_sources >"$raw_current"
scan_color_state_sources >"$color_current"
scan_visual_content_sources >"$visual_current"

check_manifest \
  "Raw glyph source manifest" \
  "Scripts/lib/accessibility_raw_glyph_sources.txt" \
  "$raw_current"

check_manifest \
  "Color-state source manifest" \
  "Scripts/lib/accessibility_color_state_sources.txt" \
  "$color_current"

check_manifest \
  "Visual-content source manifest" \
  "Scripts/lib/accessibility_visual_content_sources.txt" \
  "$visual_current"

check_listening_docs

rm -f "$raw_current" "$color_current" "$visual_current"

if [ "$failures" -ne 0 ]; then
  exit 1
fi
