#!/usr/bin/env python3
"""Independent fixture census and base/head change-detection checks."""
import tempfile
import unittest
from pathlib import Path

from source_inventory import census, compare, render


class InventoryTests(unittest.TestCase):
    def test_manifest_ownership_and_exclusions(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            sources = {"Tests/Support/Helper.swift": "// comment\n\nlet x = 1\n",
                       "Custom/Case.swift": "@Test func example() {}\n",
                       "Vendor/V.swift": "let vendored = 1\n",
                       "Custom/Generated.swift": "// Generated by fixture\nlet x = 2\n"}
            for name, content in sources.items():
                path = root / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
            manifest = {"targets": [
                {"name": "Support", "type": "library", "path": "Tests/Support", "sources": ["Helper.swift"]},
                {"name": "Cases", "type": "test", "path": "Custom", "sources": ["Case.swift", "Generated.swift"]},
                {"name": "Vendor", "type": "library", "path": "Vendor", "sources": ["V.swift"]}]}
            result = census(root, manifest, {}, "fixture")
            self.assertEqual(len(result["files"]), 2)
            self.assertEqual(len(result["excluded"]), 2)
            helper = next(r for r in result["files"] if r["target"] == "Support")
            self.assertEqual((helper["kind"], helper["lines"]), ("library", 3))
            self.assertIn("1 unclassified", render(result))
            self.assertEqual(result, census(root, manifest, {}, "fixture"))

    def test_add_delete_rename_target_move_and_edit(self):
        def row(path, target="A", digest="same", lines=1):
            return dict(path=path, target=target, sha256=digest, lines=lines)
        before = {"files": [row("old"), row("deleted", digest="delete"), row("moved", digest="move"), row("edited", digest="before")]}
        after = {"files": [row("renamed"), row("added", digest="add"), row("moved", target="B", digest="changed"), row("edited", digest="after", lines=2)]}
        self.assertEqual({r["change"] for r in compare(before, after)}, {"rename", "deleted", "added", "target-move", "modified"})

    def test_duplicate_content_is_not_guessed_as_a_rename(self):
        before = {"files": [dict(path="a", target="A", sha256="x"), dict(path="b", target="A", sha256="x")]}
        after = {"files": [dict(path="c", target="A", sha256="x")]}
        self.assertEqual([r["change"] for r in compare(before, after)].count("rename"), 0)


if __name__ == "__main__":
    unittest.main()
